version: '3.8'

services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - /opt/df-bootcamp-arq-software/h2db:/opt/df-bootcamp-arq-software/h2db
        environment:
            - SPRING_PROFILES_ACTIVE=dev
        networks:
            - app-network

volumes:
    app-data:
        driver: local

networks:
    app-network:
        driver: bridge
