version: '3.8'

services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - app-data:/opt/df-bootcamp-arq-software/db
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        networks:
            - app-network

volumes:
    app-data:
        driver: local

networks:
    app-network:
        driver: bridge
